[package]
name = "rpmsg-lite"
version = "0.1.0"
authors = ["Jon Lamb"]

[dependencies]
cortex-m = "0.5.7"
bare-metal = "0.2.3"
vcell = "0.1.0"
nb = "0.1.1"

[dependencies.void]
default-features = false
version = "1.0.2"

#[features]
#default = ["cortex-m-remote", "cortex-a-master"]
