[package]
name = "sel4twinkle-alloc"
version = "0.0.1"
authors = ["jonlamb-gh <lamb.jon.io@gmail.com>"]

[dependencies]
#libsel4-sys = {git = "https://github.com/jonlamb-gh/libsel4-sys.git", branch = "master"}
libsel4-sys = {path = "../libsel4-sys"}
