[package]
name = "m4-firmware"
version = "0.1.0"
publish = false

[dependencies]
cortex-m = "0.5.7"
cortex-m-rt = "0.6.3"
bare-metal = "0.2.3"

[profile.release]
codegen-units = 1 # better optimizations
debug = true
lto = true # better optimizations
