[package]
name = "m4-firmware"
version = "0.1.0"
publish = false

[dependencies]
cortex-m = "0.5.7"
cortex-m-rt = "0.6.3"

[dependencies.rpmsg-lite]
path = "rpmsg-lite/"
version = "0.1.0"

[profile.release]
codegen-units = 1 # better optimizations
debug = true
lto = true # better optimizations
